name: 'Create A File'
description: 'Create a file'
branding:
  icon: 'file'  
  color: 'green'
inputs:
  path:
    description: 'Path from cwd where file is to be created'
    required: true
    default: ''
  name:
    description: 'The name of the file to be created with extention'
    required: true
  params:
    description: 'The key-values pairs of the file'
    required: true
    default: ''
runs:
  using: 'node12'
  main: 'index.js'